### PR TITLE
fix: test bellman changes to try to avoid verify deadlock

### PR DESCRIPTION
**Pull request by cryptonemo**

### CODE REVIEW

**Comment by cryptonemo** [comment]
WIP: Trying to see if we can narrow down the bellman verify issue

**Comment by cryptonemo** [comment]
Requires: https://github.com/filecoin-project/bellperson/pull/196

**Review by arajasek — APPROVED** [review]

**Comment by jennijuju** [comment]
CI hangs..

**Comment by cryptonemo** [comment]
> CI hangs..

The leak checks take hours

**Pull request merged**
