### PR TITLE
fix: update proofs release to latest

### PR DESCRIPTION
**Pull request by cryptonemo**

### CODE REVIEW

**Comment by cryptonemo** [comment]
@magik6k @Kubuxu The CI may not quite be happy, but this is the PR to test out for picking up the new proofs release.

**Review by porcuquine — APPROVED** [review]
This looks right. If CI passes and downstream builds, seems fine.

**Comment by cryptonemo** [comment]
@magik6k @Kubuxu CI is good now except for a `go_lint` failure -- if this is something you can handle (or ignore), it would be appreciated.

**Comment by cryptonemo** [comment]
@Kubuxu Pretty sure it's just failing because of the LD_LIBRARY_PATH not being set.  Slack is delaying my responses.  Unfortunately, the hwloc lib is not statically linked like I was hoping, and there is a lead on the rust bindings to help it, but it's not happening immediately.

**Comment by cryptonemo** [comment]
I'll push an update to test that out shortly @magik6k @Kubuxu

**Comment by cryptonemo** [comment]
Hrm, ok, maybe it is go related: https://github.com/dominikh/go-tools/issues/646  Not entirely sure what this means yet.

**Comment by cryptonemo** [comment]
Based on lotus testing, I am linking a possible neptune version issue with this PR: https://github.com/filecoin-project/rust-fil-proofs/issues/1320#issuecomment-711442048

**Comment by cryptonemo** [comment]
@magik6k @Kubuxu Any chance we can get lotus re-testing with this?  This updates neptune and somehow fixed the go-lint issue (?) -- perhaps people with PC1 problems will have better luck now.

**Review by magik6k — APPROVED** [review]
Looks good, and seems to work pretty well in testing

**Pull request merged**
