### PR TITLE
Update fvm integration for FIP0031

### PR DESCRIPTION
**Pull request by vyzo**
Required for https://github.com/filecoin-project/lotus/pull/8429
Blocked on https://github.com/filecoin-project/ref-fvm/pull/448 and crate release

Note: Cargo points to my local dev env, which will make CI very angry. I will update once https://github.com/filecoin-project/ref-fvm/pull/448 merges and the crate is released.

### CODE REVIEW

**Review by arajasek — APPROVED** [review]

**Review by arajasek — APPROVED** [review]

**Comment by Stebalien** [comment]
I am _really_ confused. Passing the manifest into the FVM was, IIRC, a _hack_ to get this working for nv15. For nv16, the manifest should be linked into the state-tree via the upgrade. Why are we passing it here?

**Review by Stebalien — DISMISSED** [review]
(blocked)

**Comment by vyzo** [comment]
I think that will happen starting with nv17, where we can pass None.

The migrate has to already have happened to be able to do that. Passing it in allows us to test.

**Comment by Stebalien** [comment]
> I think that will happen starting with nv17, where we can pass None.

NV16 _is_ the network version with the manifest linked into the state-tree. And yes, the migration has to pass to test. Or we need to link in the manifest when we create the genesis state, which we can and should do.

**Comment by Stebalien** [comment]
We likely need to pass in the CAR in https://github.com/filecoin-project/lotus/blob/a709a0a6824797da416dbdf9de345ae55004fbf5/chain/gen/genesis/genesis.go#L160.

**Comment by Stebalien** [comment]
Discussed synchronously. We're going to keep this _for testing_.

- For the real NV16, we'll set the manifest in the upgrade.
- For future test networks, we'll set it in genesis.

But having the ability to _override_ the manifest is still useful.

**Review by Stebalien — APPROVED** [review]

**Pull request merged**
