### PR TITLE
feat: update to the improved error handling in proofs

### PR DESCRIPTION
**Pull request by cryptonemo**
feat: some shell logic re-factoring

### CODE REVIEW

**Comment by Stebalien** [comment]
(converting to draft till we depend on released crates)

**Comment by cryptonemo** [comment]
@magik6k If you have a way to test those kinds of failures you were seeing, this is the branch to test.  It's all draft at this point due to releases being required first as @Stebalien pointed out above.

**Comment by magik6k** [comment]
I'll try to get this tested tomorrow, just got a sector in this state again

**Comment by magik6k** [comment]
Much better now, nothing panics and the call is just returning `error: failed to compute seal proof: failed to generate vanilla proof: Invalid encoding proof generated at layer 1, challenge_index 2` as expected.

**Comment by cryptonemo** [comment]
Requires https://github.com/filecoin-project/rust-filecoin-proofs-api/pull/97

**Review by vmx — COMMENTED** [review]
In the CircleCI config we use 1.67 for rustfmt. I don't expect that it makes much difference, but i think it would make sense to keep it in sync with the version we use in the `rust-toolchain.toml`.

**Comment by cryptonemo** [comment]
@magik6k @Stebalien This is pointing to a real proofs release now and is good to go on our side.  Edit or merge at will.

**Review by magik6k — APPROVED** [review]

**Pull request merged**
