### PR TITLE
fix: use correct default features for the published binaries

### PR DESCRIPTION
**Pull request by cryptonemo**

### CODE REVIEW

**Comment by cryptonemo** [comment]
@travisperson The darwin build environment looks broken -- let me know if you can approve anyway or have ideas on how to resolve that.

**Review by travisperson — APPROVED** [review]

**Comment by cryptonemo** [comment]
Hrm, I just realized OS X is required, so I can't merge anyway right now.

**Comment by cryptonemo** [comment]
@dignifiedquire Do you have git powers to merge this PR?

**Comment by dignifiedquire** [comment]
afaik we also generate prebuilts on macos, so we should fix those builds before triggering a new set of prebuilts

**Comment by cryptonemo** [comment]
> afaik we also generate prebuilts on macos, so we should fix those builds before triggering a new set of prebuilts

Hrm, yes we do -- didn't realize.  I've asked Infra to take a look at the CI machine.

**Pull request merged**
