### PR TITLE
feat: add FFI_USE_CUDA_SUPRASEAL env variable (#425)

### PR DESCRIPTION
**Pull request by vmx**
Make it possible to build the FFI with SupraSeal enabled, which should lead to better performance during C2.

### CODE REVIEW

**Review by magik6k — APPROVED** [review]

**Comment by Stebalien** [comment]
Wait for @arajasek before merging.

**Comment by arajasek** [comment]
I don't think we want this in 1.24.0. It's landed in `master`, so it'll go out in the next release?

**Comment by vmx** [comment]
We pushed hard to get this into 1.24. It was just accidentally not merged.

**Comment by arajasek** [comment]
^What @Stebalien said. Basically, 1.24.0 should be _exactly_ what's in https://github.com/filecoin-project/filecoin-ffi/commits/release/lotus-v1.23.4, plus anything _needed_ for SynthPoRep / nv21.

**Comment by vmx** [comment]
> This _will_ be in 1.25 which will be released at the same time.

Just to make sure I understand this correctly: whether this change is in 1.24 or 1.25, people will be able to enable this feature *on the same day*. The only difference is that they need to use 1.25 instead of 1.24, correct?

**Comment by arajasek** [comment]
> > This _will_ be in 1.25 which will be released at the same time.
> 
> Just to make sure I understand this correctly: whether this change is in 1.24 or 1.25, people will be able to enable this feature _on the same day_. The only difference is that they need to use 1.25 instead of 1.24, correct?

Yes, that is correct.

**Comment by vmx** [comment]
> Yes, that is correct.

Cool, I just wanted to make sure that feature gets in the hands of people as soon as possible, which is the case (I don't mind which version that is). Hence I'm closing his PR.

**Pull request closed without merging**
