### PR TITLE
don't require rustup

### PR DESCRIPTION
**Pull request by coryschwartz**
rustup isn't actually required to build.

The specific reason I'm requesting this change that the macos brew installation could include rust as a dependency, but it seems inappropriate to run rustup-init as part of the build. Instead, I should be able to use the system rust toolchain.

There are probably other situations where you want to build FFI and use the system rust.

### CODE REVIEW

**Comment by cryptonemo** [comment]
Should probably check for `cargo` and `rust` though, no?

**Comment by coryschwartz** [comment]
oh sure, I can change the check for 'rust' rather than 'rustup'

**Comment by dignifiedquire** [comment]
If you do this, you should check that `rustc --version` matches whatever is in https://github.com/filecoin-project/filecoin-ffi/blob/master/rust/rust-toolchain otherwise you will break the assumptions made. Rustup will use the version specified in that file, but if you use a system rust install that will not be the case, and things might start to break suddenly

**Comment by vmx** [comment]
I'm closing this PR as using rustup is the preferred way to do it.

**Pull request closed without merging**
