### PR TITLE
chore: update FVM to v4.1.2 and v3.9.0

### PR DESCRIPTION
**Pull request by rjan90**
Prepering a PR updating FVM to the new FVM-release (v4.1.2) that is coming, due to https://github.com/filecoin-project/ref-fvm/pull/1978

### CODE REVIEW

**Comment by Stebalien** [comment]
NOTE: I'll also be releasing a new version in the v3 line.

**Comment by rjan90** [comment]
Ack! I will wait for the new version in the v3 line version to land and update that in this PR as well.

**Comment by Stebalien** [comment]
@rjan90 this should be good to go. Can you give my code a review?

**Comment by Stebalien** [comment]
(may be we should have just done this as two PRs...)

**Review by rjan90 — COMMENTED** [review]
I do not have approval rights, but the changes for updating the versions looks good to me.

When it comes to the changes in `/fvm/engine.rs`, those are a little bit outside my knowledge area. But they do seem correct to me from the standpoint that we are now changing `ExecutionEvent::InvokeActor` to include the actor's ID and state-object (codeCID, balance, current state root, delegated address, and sequence/nonce)

**Comment by Stebalien** [comment]
I tagged a release (need it in my lotus tracing work).

**Pull request merged**
